### ISSUE TITLE
Setup failed for custom integration ac_infinity: Requirements for ac_infinity not found: ['ac-infinity-ble==0.4.2'].

### ISSUE THREAD

**Issue by Kathou99** [hunterjm/ac-infinity-hacs#6] opened 2023-09-07 00:57 UTC
Hi, how I can fix this?

Logger: homeassistant.setup
Source: setup.py:209
First occurred: 20:46:47 (1 occurrences)
Last logged: 20:46:47

Setup failed for custom integration ac_infinity: Requirements for ac_infinity not found: ['ac-infinity-ble==0.4.2'].

**Comment by MRobi1** [comment] 2023-09-07 12:50
Same issue on update to 2023.9.0

![image](https://github.com/hunterjm/ac-infinity-hacs/assets/34860474/468a852f-93ae-4222-9506-3eb2771100c9)

**Comment by dagrah** [comment] 2023-09-07 14:59
Same here since update 2023.9.0

**Comment by mikeybatoz** [comment] 2023-09-07 17:10
Have you tried to manually download the file using the terminal?

I did a quick scan of the integration on here but did not see that library added

**Comment by grssll** [comment] 2023-09-08 09:27
I have tried the teminal and still getting the same error

**Comment by grssll** [comment] 2023-09-08 09:28
2023-09-08 19:25:03.832 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ac_infinity which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-09-08 19:25:51.572 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration ac_infinity: Requirements for ac_infinity not found: ['ac-infinity-ble==0.4.2'].
homeassistant.loader.IntegrationNotFound: Integration 'ac_infinity' not found.
homeassistant.requirements.RequirementsNotFound: Requirements for ac_infinity not found: ['ac-infinity-ble==0.4.2'].
homeassistant.requirements.RequirementsNotFound: Requirements for ac_infinity not found: ['ac-infinity-ble==0.4.2'].

**Comment by mikeybatoz** [comment] 2023-09-08 09:35
pip install ac-infinity-ble

or manually add it to the custom component after downloading it to your server

https://pypi.org/project/ac-infinity-ble/

**Comment by grssll** [comment] 2023-09-08 10:08
I've ran the command and installed the BLE but still integration cant be loaded.

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 109.1 MB/s eta 0:00:00
Installing collected packages: usb-devices, multidict, idna, frozenlist, dbus-fast, charset-normalizer, attrs, async-timeout, aiofiles, yarl, bleak, aiosignal, aiohttp, mac-vendor-lookup, bluetooth-adapters, bleak-retry-connector, ac-infinity-ble
Successfully installed ac-infinity-ble-0.4.2 aiofiles-23.2.1 aiohttp-3.8.5 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.1.0 bleak-0.20.2 bleak-retry-connector-3.1.1 bluetooth-adapters-0.16.1 charset-normalizer-3.2.0 dbus-fast-1.95.2 frozenlist-1.4.0 idna-3.4 mac-vendor-lookup-0.1.12 multidict-6.0.4 usb-devices-0.4.1 yarl-1.9.2

**Comment by mikeybatoz** [comment] 2023-09-08 10:10
I’d try downloading the file and adding it into  the custom component then. I can work on a fox later to see if I can do it but I don’t use this integration. I use the clunky manual method

**Comment by grssll** [comment] 2023-09-08 10:34
Manual method didnt work. If you have time later on please see what you can do.
Thanks

**Comment by douginoz** [comment] 2023-09-09 06:51
> I’d try downloading the file and adding it into the custom component then. I can work on a fox later to see if I can do it but I don’t use this integration. I use the clunky manual method

@mikeybatoz 
Can you elaborate on how to add it into the custom component?  I assume this component is installed via HACS.  I'm not aware of any way to modify something installed that way.  And since I'm running HAOS supervised, I can't manually add anything (well, I can pretend ssh into it but that's just a docker shell and doesn't affect the actual underlying HA).

Alternatively, could you explain what the 'clunky manual method' is?

By the way, the error in the error log is:
`Unable to install package ac-infinity-ble==0.4.2: ERROR: Cannot install ac-infinity-ble==0.4.2 because these package versions have conflicting dependencies. `

**Comment by Kathou99** [comment] 2023-09-13 22:01
any update?

**Comment by mikeybatoz** [comment] 2023-09-15 10:42
Wasn’t able to get this integration to work, there’s another that does the same thing but works. If you add this to your home assistant it will cause both not to function. Tried installing via app daemon but still nothing on a flashed r Pi4

**Comment by dagrah** [comment] 2023-09-15 15:01
When you remove this integration and install that one you mention, does it then work?
Whats the integration you tried? :)

**Comment by mikeybatoz** [comment] 2023-09-15 15:04
https://github.com/dalinicus/homeassistant-acinfinity/issues. Had to backup from before installing this it really F’s the system

**Comment by AustinBrunkhorst** [comment] 2023-09-15 15:42
The root cause is `ac-infinity-ble` requires a different minor version of `bleak` that Home Assistant core recently moved off of. I have a fix here: https://github.com/hunterjm/ac-infinity-ble/pull/8 - it looks like @hunterjm may be unavailable so we'll have to wait until they get a chance to merge the changes.

**Comment by AustinBrunkhorst** [comment] 2023-09-15 16:12
I made a fork of this repo with `ac-infinity-ble` included locally as a workaround until @hunterjm is available. 

**Workaround instructions**
1. Remove `hunterjm/ac-infinity-hacs` as a custom repository in HACS (you can add it back later. This won't change your existing config entries).
2. Add `AustinBrunkhorst/ac-infinity-hacs` as a custom repository in HACS.
3. Download the `ac_infinity` HACS integration.
4. Restart Home Assistant.

**Comment by hunterjm** [comment] 2023-09-15 17:55
@AustinBrunkhorst - If you open a PR, I'll merge it in and cut a release.

edit: I see the PR in the ble repo - merging now.

**Comment by AustinBrunkhorst** [comment] 2023-09-15 17:57
> @AustinBrunkhorst - If you open a PR, I'll merge it in and cut a release.

Thanks, PR is here: https://github.com/hunterjm/ac-infinity-ble/pull/8

**Comment by hunterjm** [comment] 2023-09-15 18:18
Fixed in 1.0.3

**Closed as completed by hunterjm** 2023-09-15 18:18 UTC
